defmodule UrlShortner.EventBroker.Event do
  @moduledoc """
  Behaviour for business events that are generated in the system

  So we can know all events that can be generated by the system and
  where they are handled.

  To create a new business event you have to add a new struct that holds
  the info needed for you to handle the event in `UrlShortner.EventBroker.Events.$MODULE`
  but also implement the functions defined in the behaviour here (`#{__MODULE__}`).
  """

  alias UrlShortner.EventBroker.Events

  @type kind :: %{}

  @callback handle(kind()) :: :ok
end
